### ISSUE TITLE
SRPM build - command 'git describe' failed

### ISSUE THREAD

**Issue by shreyaspapi** [packit/packit-service#732]
While testing copr-build on gitlab - https://gitlab.com/packit-service/hello-world/-/merge_requests/6, getting [this](https://packit.shreyasp.me:8443/srpm-build/7/logs) error.

I already have tags pushed on the hello-world repository, still it gives an error -

```
7:08:59.977 base_git.py       DEBUG  Command handler: RunCommandType.local
17:08:59.977 utils.py          DEBUG  Command: git --no-pager tag --list
WARNING  There are no tags in the repo, `git describe` will very likely fail.
17:09:00.002 utils.py          DEBUG  Command: git describe --abbrev=0 --tags --match *
17:09:00.016 utils.py          DEBUG  fatal: No names found, cannot describe anything.
ERROR    Command 'git describe --abbrev=0 --tags --match *' failed.
17:09:00.017 utils.py          DEBUG  Command stderr: fatal: No names found, cannot describe anything.
```

**Comment by TomasTomecek** [comment]
Interesting, works for me just fine locally:
```
$ git clone https://gitlab.com/packit-service/hello-world
Cloning into 'hello-world'...
warning: redirecting to https://gitlab.com/packit-service/hello-world.git/
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 68 (delta 36), reused 54 (delta 29), pack-reused 0
Receiving objects: 100% (68/68), 8.95 KiB | 2.98 MiB/s, done.
Resolving deltas: 100% (36/36), done.

$ git --no-pager tag --list
0.0.1
0.0.2
0.1.0
v0.0.1
v0.0.1.dev
```

**Comment by shreyaspapi** [comment]
The error is occurring randomly on Gitlab while making new Merge Request. Retriggering is solving the issue.

**Comment by TomasTomecek** [comment]
so it's a race condition, we would need more info about the git repository state to know what exactly is happening and why

**Comment by lachmanfrantisek** [comment]
This is randomly appearing also on our instances, isn't it?

**Comment by TomasTomecek** [comment]
I fixed something related in here recently: https://github.com/packit-service/packit/commit/0d13c7d605b8ead823b47f5e469855157698c4b8

would that be a fix for this as well?

**Comment by lachmanfrantisek** [comment]
> would that be a fix for this as well?

Not sure but might be...

@shreyaspapi can you reproduce this now as well?

**Comment by shreyaspapi** [comment]
@TomasTomecek I can't figure out the exact issue here. 

@lachmanfrantisek Still occurring randomly.

**Comment by lachmanfrantisek** [comment]
@shreyaspapi Can we close it?

**Comment by TomasTomecek** [comment]
Given the lack of response I am going to close, please reopen if the issue persists.
